CREATE TYPE property_type AS ENUM ('HOME', 'HOTEL');
CREATE TYPE amenity_type AS ENUM ('ROOM_AMENITY', 'PROPERTY_AMENITY');
CREATE TYPE booking_status AS ENUM ('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED');
